apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-release
spec:
  workspaces:
  - name: releases
    workspace: workspace

  params:
    - name: version
      type: string
    - name: release-notes
      type: string
    - name: branch
      type: string
    - name: repo
      type: string
    - name: rel_ver
      type: string

  steps:
    - name: prepare-release
      image: ubi9/go-toolset:latest
      script: |
        git config --global --add safe.directory /workspace/releases
        make -C /workspace/releases prepare_release version=$REL_VER

      env:
        - name: VERSION
          value: $(params.version)
        - name: RELEASE_NOTES
          value: $(params.release-notes)
        - name: BRANCH
          value: $(params.branch)
        - name: REPO
          value: $(params.repo)
        - name: REL_VER
          value: $(params.rel_ver)

