apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-release
spec:
  workspaces:
  - name: releases
  params:
    - name: rel_ver
      type: string
      value: 1.0
  steps:
    - name: prepare-release
      image: ubi9/go-toolset:latest
      script: |
        git config --global --add safe.directory /workspace/releases/sources
        make -C /workspace/releases/sources prepare_release version=$REL_VER
      env:
        - name: REL_VER
          value: $(params.rel_ver)

