apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: github-upload-release
spec:
  workspaces:
  - name: releases
  params:
    - name: repo
      type: string
      value: https://github.com/enriquebelarte/terraform-provider-rhcs-tests
    - name: githubAppId
      type: string
      value: 811192
    - name: githubAppInstallationId
      type: string
      value: 46731356
    - name: IMAGE_URL
  steps:
    - name: generate-gh-token
      image: ubi9:latest
      script: |
        curl -sL "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64" > jq
        chmod +x jq
        GH_VERSION=$(curl -s https://api.github.com/repos/cli/cli/releases/latest | ./jq -r '.tag_name') 
        curl -sL "https://github.com/cli/cli/releases/download/$GH_VERSION/gh_${GH_VERSION#v}_linux_amd64.tar.gz" | tar xz --strip-components=2  
        chmod +x gh
        cp /workspace/releases/source/build/generate_jwt .
        chmod +x generate_jwt
        pem=${GH_KEY} ./generate_jwt $GH_APP_ID
        # get the token by POSTING to the url:
        github_api_url="https://api.github.com/app/installations/${GH_INS_ID}/access_tokens"
        JWT=$(cat myjwt)
        tokens=$(curl -s -X POST \
            -H "Authorization: Bearer ${JWT}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${github_api_url}" )
        token=$(echo "$tokens" | ./jq -r '.token')
        mkdir -p /workspace/releases/files
        echo $token > /workspace/releases/files/github_token         
        pwd 
      env:
        - name: GH_APP_ID
          value: $(params.githubAppId)
        - name: GH_INS_ID
          value: $(params.githubAppInstallationId)
        - name: GH_KEY
          valueFrom:
            secretKeyRef:
              name: github-app-key
              key: key
    - name: copy-binaries-from-builder
      image: $(params.IMAGE_URL)
      script: |
        mkdir -p /workspace/releases/binaries
        cp /releases/* /workspace/releases/binaries/
        cp /tmp/rel_ver /workspace/releases/rel_ver
    - name: create-release-from-binaries
      image: ubi9:latest
      script: |
        curl -L https://github.com/cli/cli/releases/download/v2.32.1/gh_2.32.1_linux_amd64.tar.gz --output gh_2.32.1_linux_amd64.tar.gz  
        tar -zvxf gh_2.32.1_linux_amd64.tar.gz 
        mv gh_2.32.1_linux_amd64/bin/gh /bin/gh 
        chmod +x /bin/gh 
        pwd
        token=$(cat /workspace/releases/files/github_token)
        export GITHUB_TOKEN=$token
        cd /workspace/releases/binaries
        export REL_VER=$(cat /workspace/release/rel_ver)
        gh release create v"$REL_VER" *.zip *.json *SHA256SUMS --repo $REPO --title "Release v$REL_VER"
        rm -f /workspace/releases/files/github_token
      env:
        - name: REPO
          value: $(params.repo)
